### ISSUE TITLE
It is not possible to create a motion.

### ISSUE THREAD

**Issue by jakzilla** [JoinColony/colonyDapp#2878] opened 2021-11-13 19:27 UTC
When a motion is attempted transaction fails and Gas station throws the following error:

`Send error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32010,"message":"Filtered"}}}'`

https://blockscout.com/poa/xdai/tx/0xf9d656bd97698fe18e8efdc302d1229b856a41b3ccaef93b793011ddc8fb606a

![Screenshot 2021-11-13 at 19 12 12](https://user-images.githubusercontent.com/4774274/141656681-84b73ecb-0b74-4c19-a3ae-4e8c92e8ffe1.png)
![Screenshot 2021-11-13 at 19 24 20](https://user-images.githubusercontent.com/4774274/141656684-22778d2d-d101-4d0e-a65d-ce6a79a62db7.png)

**Comment by rdig** [comment] 2021-11-13 19:47
Is this QA or production?

But two things to consider:
- subrgraph was down today _(is still down?)_
- this looks like a problem with the RPC endpoint, so we'll need @area 's eyes as well

**Comment by jakzilla** [comment] 2021-11-14 19:06
This was production. Was a report from Shapeshift that I was able to replicate. I did say I thought it was probably a problem with either the Graph or the endpoint so I'm feeling quite pleased with myself. :)

**Comment by rdig** [comment] 2021-11-14 19:30
It's apparently the `london` hardfork that tripped up the RPC endpoint.

There's also some funky thing going on with the gas estimation (from the oracle).

We'll check this out tomorrow.

**Comment by rdig** [comment] 2021-11-15 15:05
Pushed a fix for the gas estimation to production. 

This fixes this issues.

**Closed by rdig** 2021-11-15 15:05 UTC

**Comment by thycommodore** [comment] 2021-11-20 13:49
@rdig I'm QA'ing and running into this issue during the colony creation process during different steps.

https://d.pr/i/2m6dHB
https://d.pr/i/prJ1w3
https://d.pr/i/xvp3pT

To be specific, I tried creating 3 different colonies. Each colony hit this error at some point during the creation experience.

**Comment by rdig** [comment] 2021-11-20 14:01
This problem was related to gas estimation. It's exacerbated by the fact that the RPC endpoint no longer displays human readable error outputs _(basically making all error messages look the same)_.

The fix for this is deployed on QA currently, so  I suspect it's something differently althogether.

There is a way to check however. Manually set the gas send sending a transaction to 2 gwei _(or 3 gwei to be safe)_. If you still get an error after this, than your error is something else entirely.

**Comment by thycommodore** [comment] 2021-11-20 14:07
As Raul pointed out in his prior comment, this can be worked around (for QA purposes) by increasing the gas manually.

**Comment by rdig** [comment] 2021-11-20 14:08
Ok, I've tested this. It's the same, but not the same.

It's the same in the sense that it's a gas problem.

It's not the same in the sense that it's not the dapp's fault.

The problem comes from the gas prices oracle we're using for the xdai network _(blockscout in this case)_, which returns 1 gwei for all 3 _(slow/avg/fast)_

I actually don't know how we can solve this properly ?

**Comment by rdig** [comment] 2021-11-20 14:09
Here's what I'm talking about:

![Screenshot from 2021-11-20 16-09-14](https://user-images.githubusercontent.com/1193222/142729350-421602f0-4e91-4d6a-9f65-75e104088979.png)

At least one of those values should be 2, or higher

**Comment by thycommodore** [comment] 2021-11-20 14:53
@rdig I can confirm that workaround resolution does appear to work every time. So does seem isolated to the oracle. 

Would a bad workaround be "check if oracle returns 1, 1, 1," if it does then modify it to be "1, 2, 3"? I'm assuming it's a bad workaround because we're injecting a "oracle-like" function that's not really an oracle & there could be some downstream issues?

**Comment by rdig** [comment] 2021-11-20 14:55
What happens if the network then suddenly has a spike (like a token sale would certainly facilitate) and the new minimum becomes 4 ?

We're getting this error again.

That's why we need the oracle, to tell us real-time network gas costs

**Comment by thycommodore** [comment] 2021-11-20 15:13
@rdig just got a 1.02 estimate for the first time in over a few hours and it appears it might be back up & running. 

![image](https://user-images.githubusercontent.com/89165465/142731567-17cf34db-697d-48b1-95cb-3f331d13aea2.png)
