### ISSUE TITLE
Coin Machine doesn't present TOS agreement which results in an estimation error

### ISSUE THREAD

**Issue by thycommodore** [JoinColony/colonyDapp#3031] opened 2021-12-13 15:28 UTC
## Steps to reproduce

1. Create new colony
2. Enable whitelist (TOS & whitelist)
3. Enable coin machine
4. Send tokens to coin machine to start it
5. Attempt to buy tokens

## Expected behaviour

* User receives TOS agreement
* User successfully buys tokens

## Actual behaviour

* Estimation error 

![image](https://user-images.githubusercontent.com/89165465/145840108-cb57b93f-113d-4d82-a330-cc97f540bd35.png)

**Comment by rdig** [comment] 2021-12-20 09:15
I think there's something else here at play. As before the Agreement modal shows up, you first to whitelist your address. 

If your address is not whitelisted, the Agreement can't show up, as they are different steps

**Comment by chinins** [comment] 2021-12-20 17:36
The address was whitelisted. The issue is different and is linked to what we discussed on Friday. The app doesn't see extension as enabled so the agreement dialog doesn't pop up. If you refresh the app before buying tokens or if a different person loads a page once the extension is installed the agreement modal appears and then there is no error in buying tokens.

I am closing this issue because we have another issue about this problem and I will mention this issue there.

**Closed by chinins** 2021-12-20 17:36 UTC
Labels: bug
