### ISSUE TITLE
Deactivating Address Produced the (a) wrong Action Message

### ISSUE THREAD

**Issue by rdig** [JoinColony/colonyDapp#3434] opened 2022-06-08 11:58 UTC
![Screenshot from 2022-06-08 14-46-42](https://user-images.githubusercontent.com/1193222/172610530-4ddec69b-2a95-4756-bb6c-acd2aa89fcf8.png)

I think the message was not implemented to compare the deactivation of the address, so the action we're reusing for this doesn't know about it.

This is only tested on the #3190 branch, so most likely it's affected by something in it

**Comment by danbr** [comment] 2022-06-08 16:55
> 
> I think the message was not implemented to compare the deactivation of the address, so the action we're reusing for this doesn't know about it.
> 
> This is only tested on the #3190 branch, so most likely it's affected by something in it

I get this:
<img width="1040" alt="Screenshot 2022-06-08 at 17 50 31" src="https://user-images.githubusercontent.com/582700/172673349-67bc50c8-573f-4b37-87ed-50f6e71442fe.png">

Should this be considered an appropriate message when deactivating an address?
In fact it seems to be used for both adding & removing addresses.

**Comment by rdig** [comment] 2022-06-08 16:58
> I get this:

Then it must have been something on my end

> Should this be considered an appropriate message when deactivating an address?

Yes it is.

I think this is a non-issue, as it might have just been something with IPFS on my end when testing. Feel free to close this.

**Comment by danbr** [comment] 2022-06-08 17:05
Closed as unreproducible!!

**Closed by danbr** 2022-06-08 17:05 UTC
Labels: bug
