### ISSUE TITLE
Funding task with token that isn't available

### ISSUE THREAD

**Issue by collinvine** [JoinColony/colonyDapp#1535] opened 2019-07-16 21:31 UTC
## Steps to reproduce

1. Create a new colony and BYOT (I used DAI)
  a. interestingly, I used the mainnet DAI address [here](https://etherscan.io/token/0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359) instead of the Goerli one [here](https://goerli.etherscan.io/token/0x72560b830ced423fbb9ec1ae8d01b41f015a5f21).
2. Create a new task
3. Assign a worker and fund the task (I add 1 DAI)
4. The transaction went through, even though I haven't sent DAI to the Colony

## Expected behaviour

* This would fail because my colony doesn't have any DAI in its address

## Actual behaviour

* The transaction went through

![Screen Shot 2019-07-16 at 2 30 47 PM](https://user-images.githubusercontent.com/15755488/61331204-53a9fd00-a7d6-11e9-9fa5-d11cd5b06be0.png)

* After a refresh, the token amount is not displayed but finalize button is active:

![Screen Shot 2019-07-16 at 2 36 31 PM](https://user-images.githubusercontent.com/15755488/61331673-2c076480-a7d7-11e9-806e-77891270e983.png)

* Clicking `finalize` tx fail of course:
![Screen Shot 2019-07-16 at 2 38 30 PM](https://user-images.githubusercontent.com/15755488/61331758-63761100-a7d7-11e9-9004-5062904ac99b.png)

* After the task is cancelled, the **DAI 1** reappears
![Screen Shot 2019-07-16 at 2 41 24 PM](https://user-images.githubusercontent.com/15755488/61331941-daaba500-a7d7-11e9-9086-235882f9f166.png)

## Suggestions (optional)

* Could validate if the token is available to fund the task first?

**Comment by JamesLefrere** [comment] 2019-08-26 08:54
It seems like this still can't be reproduced, unless it happened again recently?

**Comment by rdig** [comment] 2019-09-09 09:54
Closing due to not being able to reproduce, and more than two weeks have elapsed since then.

**Closed by rdig** 2019-09-09 09:54 UTC
Labels: P2, bug, cannot-reproduce
