### ISSUE TITLE
Wrong Dates and Times on Motions/Disputes

### ISSUE THREAD

**Issue by cobordism** [JoinColony/colonyDapp#3017] opened 2021-12-07 22:02 UTC
## Steps to reproduce

Create a motion. Stake motion. Object to motion. Stake objection. Vote. Reveal. Finalise. Claim. Claim.

## Expected behaviour

While it might be somewhat unorthodox to both support and oppose your own motion, it does happen. Things should proceed normally.

## Actual behaviour

![dates](https://user-images.githubusercontent.com/12838530/145112707-1c851c6e-1128-456e-859e-1c3522a90b99.png)

Source:
https://qaxdai.colony.io/colony/topologic/tx/0xc0c10dfd4d9ca56464c465b49852bf37fd167ac1441b1ecaed638b054fb53ec8

The only hunch I have is that everything went too fast. Since I was doing all the staking/objecting/voting/revealing myself maybe too little time had passed and somewhere in the code it assumes implicitly that this whole process takes some minimum amount of time? Maybe that's why the displayed times are off by 1 epoch?

**Comment by agustif** [comment] 2021-12-08 00:20
I think the problem is only affecting dates in the blockchain, those dates seem to be correct on blockscout though, so I'm suspecting there's some bug in our call of TimeRelative component.

I will investigate further, but maybe casting new Date with both a possible number or date as an input, is what's failing here, and we need to treat each differently.
<img width="603" alt="Screenshot 2021-12-08 at 01 19 03" src="https://user-images.githubusercontent.com/6601142/145126069-23a4f09a-1635-4e3c-bae5-ed2dd882d2a2.png">

**Comment by rdig** [comment] 2021-12-08 07:27
This might also have to do with the timestamp coming from the subgraph, so make sure you look into that.

Also @agustif time in the local environment is not trustworthy (note that your times are actually in the future, rather then than the past), which can be affected by the reputation miner, which you had toggled on for reputation to be able to open a motion.

**Comment by agustif** [comment] 2021-12-08 19:47
OK, so far I've discovered the following:

One of the event types, SystemNetworkEvents, get their createdAt field in epoch with in miliseconds instead of seconds (so three more digits, like when multiplying/dividng by 1000 when casting the date.) That's why the error is by 1 epoch of order of magnitude more or less...

I experimented by dropping substring(0,10), but this doesn't fix it for all cases, I think I need to fix it at the root where the createdAt is generated if possible.

![image](https://user-images.githubusercontent.com/6601142/145273695-834fa5ec-3ca6-4c61-b9b9-e63c8e3ea634.png)

This happens only on events of `'type': "NetworkEvent"`

**Comment by agustif** [comment] 2021-12-08 22:51
OK, so I was able to fix this on the frontend, but we probably want to dig a bit deeper to find out why MotionCreated was still getting a miliseconds result as it's systemMesasge: {createdAt}. This is what's requiring me to use this hacky line:
`tsx
<TimeRelative
  value={new Date(Number(createdAt.toString().substr(0, 10)) * 1000)}
/>
`


Looking good otherwise though on my end!
<img width="1522" alt="Screenshot 2021-12-08 at 23 30 36" src="https://user-images.githubusercontent.com/6601142/145304007-fa1dd6a6-a595-47bf-9ba9-2c7718537e88.png">


<img width="436" alt="Screenshot 2021-12-08 at 23 42 10" src="https://user-images.githubusercontent.com/6601142/145303999-bffc141a-388c-491b-9b34-181e20143182.png">

**Comment by agustif** [comment] 2021-12-13 18:07
This was correctly resolved by @rdig in this commit https://github.com/JoinColony/colonyDapp/commit/5bcddd2c80671419dd29ea3748b8a549b127c518

So no longer applies, and the issue has been fixed properly!

**Closed by agustif** 2021-12-13 18:07 UTC
Labels: bug
